Repository always-spring01/Cpp_snake_game, pull requests merged in 2023-06, with the labels that each got.

#7 Modify Controller
  controller/GameManager.hpp
Labels: bug

#14 Modify Model
  controller/GameManager.hpp
  main.cpp
  model/Snake.hpp
Labels: documentation, enhancement

#15 Modify model
  model/Gate.hpp
  view/Board.hpp
Labels: documentation

#16 Modify Controller
  controller/GameManager.hpp
  view/Board.hpp
Labels: documentation, enhancement

#17 Hotfix
  controller/GameManager.hpp
Labels: bug

#22 Modify Gate Model
  controller/GameManager.hpp
  model/Gate.hpp
  model/Snake.hpp
  view/Board.hpp
Labels: bug, documentation

#25 Modify Controller
  controller/GameManager.hpp
Labels: documentation

#27 Modify view
  controller/GameManager.hpp
  src/rules.txt
  view/Board.hpp
  view/Map.hpp
  view/MissionBoard.hpp
Labels: documentation, enhancement

#28 Modify Controller
  controller/GameManager.hpp
  main.cpp
Labels: documentation

#29 Hotfix
  view/Board.hpp
  view/ScoreBoard.hpp
Labels: bug
